<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Setting;
use Laratrust\Models\LaratrustRole;

class SettingTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // App Core
        Setting::firstOrCreate(['key' => 'app_name', 'value' => 'zStarter', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'site_motto', 'value' => 'Empowering the power', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'app_url', 'value' => 'http://localhost/my-projects/zstarter/public_html/', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'app_language', 'value' => 'en', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'app_currency', 'value' => '₹', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'decimal_separator', 'value' => '.', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'currency_position', 'value' => 'before', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'date_format', 'value' => 'd-m-Y', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'app_address', 'value' => 'Near Bharat Petroleum, Ayodhya Nagar, Lugharwada Flat no. 5, Ground Floor, Lugharwara, Madhya Pradesh 480661', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'app_contact', 'value' => '8085122017', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'app_email', 'value' => 'info@watercane.com', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'app_logo', 'value' => '', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'app_favicon', 'value' => '', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'seo_meta_title', 'value' => 'zStarter', 'group' => 'global_seo']);
        // Global SEO
        Setting::firstOrCreate(['key' => 'seo_meta_description', 'value' => 'zStarter for Rapid Development', 'group' => 'global_seo']);
        Setting::firstOrCreate(['key' => 'seo_meta_keywords', 'value' => 'zStarter', 'group' => 'global_seo']);
        //
        Setting::firstOrCreate(['key' => 'copyright_text', 'value' => 'Copyright © {date} Book My Water | zStarter', 'group' => 'app_config']);
        Setting::firstOrCreate(['key' => 'show_social_links', 'value' => '1', 'group' => 'social_link']);
        Setting::firstOrCreate(['key' => 'facebook_link', 'value' => 'https://facebook.com/', 'group' => 'social_link']);
        Setting::firstOrCreate(['key' => 'twitter_link', 'value' => 'https://twitter.com/', 'group' => 'social_link']);
        Setting::firstOrCreate(['key' => 'instagram_link', 'value' => 'https://instagram.com/', 'group' => 'social_link']);
        Setting::firstOrCreate(['key' => 'youtube_link', 'value' => 'https://youtube.com/', 'group' => 'social_link']);
        Setting::firstOrCreate(['key' => 'linkedin_link', 'value' => 'https://linkedin.com/', 'group' => 'social_link']);
        Setting::firstOrCreate(['key' => 'mail_from_name', 'value' => 'zStarter', 'group' => 'mail_configuration']);
        Setting::firstOrCreate(['key' => 'mail_from_address', 'value' => 'info@watercane.com', 'group' => 'mail_configuration']);
        Setting::firstOrCreate(['key' => 'mail_mailer', 'value' => 'smtp', 'group' => 'mail_configuration']);
        Setting::firstOrCreate(['key' => 'mail_host', 'value' => 'smtp-relay.sendinblue.com', 'group' => 'mail_configuration']);
        Setting::firstOrCreate(['key' => 'mail_port', 'value' => '587', 'group' => 'mail_configuration']);
        Setting::firstOrCreate(['key' => 'mail_username', 'value' => 'your_email@domain.com', 'group' => 'mail_configuration']);
        Setting::firstOrCreate(['key' => 'mail_password', 'value' => 'FbwPOsdBrmJEVI5q', 'group' => 'mail_configuration']);
        Setting::firstOrCreate(['key' => 'mail_encryption', 'value' => 'ssl', 'group' => 'mail_configuration']);
        Setting::firstOrCreate(['key' => 'notification_api', 'value' => '', 'group' => 'app_api_configuration']);
        Setting::firstOrCreate(['key' => 'email_verify', 'value' => '0', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'sms_verify', 'value' => '0', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'no_of_decimal', 'value' => '2', 'group' => 'currency format']);
        Setting::firstOrCreate(['key' => 'appearance_seo_group', 'value' => 'seo_group', 'group' => 'seo_group']);
        Setting::firstOrCreate(['key' => 'notification', 'value' => '1', 'group' => 'app_config']);
        Setting::firstOrCreate(['key' => 'admin_email', 'value' => 'info@watercane.come', 'group' => 'app_config']);
        Setting::firstOrCreate(['key' => 'recaptcha', 'value' => '0', 'group' => 'app_config']);
        Setting::firstOrCreate(['key' => 'voice_input', 'value' => '0', 'group' => 'app_config']);
        Setting::firstOrCreate(['key' => 'email_notify', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'sms_notify', 'value' => '0', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'authentication_mode', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'pages_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'roles_and_permission_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'user_log_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'order_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'slider_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'wallet_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'ticket_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'lead_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'article_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'paragraph_content_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'website_enquiry_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'payment_gateway_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'payout_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'user_management_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'newsletter_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'faq_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'location_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'eKyc_verification_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'subscribers_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'item_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'add_user_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'mail_sms_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'category_management_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'subscription_plans_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'seo_tags_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'basic_details_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'manage_general_configuration_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'mail_sms_configuration_activation', 'value' => '1', 'group' => 'app_core']);
        Setting::firstOrCreate(['key' => 'group_name', 'value' => 'appearance_cookies_agreement', 'group' => 'app_config']);
        Setting::firstOrCreate(['key' => 'frontend_footer_description', 'value' => 'Description', 'group' => 'app_info']);
        Setting::firstOrCreate(['key' => 'frontend_copyright_text', 'value' => 'Copyright © ' . now()->format('Y') . ' zStarter', 'group' => 'app_info']);
        Setting::firstOrCreate(['key' => 'website_base_color', 'value' => '#377dff', 'group' => 'app_info']);
        Setting::firstOrCreate(['key' => 'website_base_hov_color', 'value' => '#377dff', 'group' => 'app_info']);
        Setting::firstOrCreate(['key' => 'seo_meta_image', 'value' => '', 'group' => 'global_seo']);
        Setting::firstOrCreate(['key' => 'facebook_client_id', 'value' => '123', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'custom_header_script', 'value' => '', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'custom_footer_script', 'value' => '', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'facebook_client_secret', 'value' => '0', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'google_client_id', 'value' => '0', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'linkedin_client_id', 'value' => '0', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'linkedin_client_secret', 'value' => '0', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'twitter_client_id', 'value' => '0', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'twitter_client_secret', 'value' => '0', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'facebook_login_active', 'value' => '1', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'global_meta_title', 'value' => '0', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'maintenance_mode', 'value' => '1', 'group' => 'app_config']);
        Setting::firstOrCreate(['key' => 'custom_header_style', 'value' => '', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'cookies_agreement_text', 'value' => '', 'group' => 'app_info']);
        Setting::firstOrCreate(['key' => 'custom_footer_style', 'value' => '0', 'group' => 'dynamic_config']);
        Setting::firstOrCreate(['key' => 'frontend_footer_address', 'value' => 'client address here', 'group' => 'app_info']);
        Setting::firstOrCreate(['key' => 'frontend_footer_phone', 'value' => '+91XXXXXXXXXX', 'group' => 'app_info']);
        Setting::firstOrCreate(['key' => 'frontend_footer_email', 'value' => 'example@domain.com', 'group' => 'app_info']);
        Setting::firstOrCreate(['key' => 'password_reset_expiry', 'value' => '10', 'group' => NULL,]);
        Setting::firstOrCreate(['key' => 'active', 'value' => 'security', 'group' => NULL,]);
        Setting::firstOrCreate(['key' => 'toggling_reports_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_resources_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_purchase_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_registration_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_sales_&_payments_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_control_products_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_setup_&_configurations_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_content_management_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_contact_enquiry_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_administrator_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_dac_activation', 'value' => '0', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_user_mfa_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_admin_mfa_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_category_management_bulk_sync', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_frontend_map_code', 'value' => '22.1109° N, 79.5444° E', 'group' => NULL,]);
        Setting::firstOrCreate(['key' => 'manage_orders_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'frontend_footer_address_secondary', 'value' => 'lugharwada seoin', 'group' => NULL,]);
        Setting::firstOrCreate(['key' => 'frontend_footer_phone_secondary', 'value' => '8085122017', 'group' => NULL,]);
        Setting::firstOrCreate(['key' => 'toggling_manage_orders_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_orders_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_orders_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_orders_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_orders_table_record_limitrch', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscribers_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscribers_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscribers_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscribers_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscribers_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscribers_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_control_payout_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_control_payout_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_control_payout_table_print', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_control_payout_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_control_payout_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_control_payout_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_item_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_item_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_item_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_item_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_item_table_print', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_item_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_item_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_manage_item_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscription_plans_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscription_plans_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscription_plans_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_subscription_plans_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_user_management_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_user_management_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_user_management_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_user_management_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_user_management_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_user_management_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_user_management_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_permission_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_website_enquiry_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_website_enquiry_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_website_enquiry_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_website_enquiry_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_website_enquiry_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_website_enquiry_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_website_enquiry_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_support_ticket_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_support_ticket_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_support_ticket_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_support_ticket_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_support_ticket_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_support_ticket_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_support_ticket_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_category_management_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_category_management_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_category_management_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_templates_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_templates_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_templates_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_templates_table_checkbox', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_templates_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_templates_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_slider_bulk_sync', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_slider_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_slider_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_slider_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_slider_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_slider_table_checkbox', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_slider_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_newsletter_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_newsletter_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_newsletter_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_newsletter_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_newsletter_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_newsletter_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_lead_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_lead_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_lead_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_lead_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_lead_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_location_activation_checkbox', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_location_activation_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_location_activation_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_faq_activation_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_faq_activation_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_faq_activation_checkbox', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_faq_activation_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_faq_activation_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_faq_activation_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_faq_activation_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_paragraph_content_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_paragraph_content_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_paragraph_content_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_paragraph_content_checkbox', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_paragraph_content_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_paragraph_content_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_seo_tags_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_seo_tags_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_seo_tags_checkbox', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_seo_tags_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_seo_tags_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_seo_tags_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_seo_tags_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_seo_tags_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_promo_code_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_pages_activation_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_pages_activation_checkbox', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_pages_activation_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_pages_activation_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_pages_activation_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_general_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_currency_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_date_mode_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_notification_verification_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_invoice_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_troubleshoot_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_control_details_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_custom_style_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_custom_script_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_blogs_bulk_delete', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_blogs_bulk_upload', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_blogs_bulk_status_update', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_blogs_table_excel_export', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_blogs_table_filter', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_blogs_table_search', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_blogs_table_record_limit', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_mail_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_sms_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_fcm_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_broadcast_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_projects_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_file_manager_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'croppedLogoData', 'value' => NULL, 'group' => NULL,]);
        Setting::firstOrCreate(['key' => 'toggling_croppedLogoData', 'value' => NULL, 'group' => NULL,]);
        Setting::firstOrCreate(['key' => 'toggling_tests_activation', 'value' => '0', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_theme_activation', 'value' => '1', 'group' => 'activation',]);
        Setting::firstOrCreate(['key' => 'toggling_marketing_activation', 'value' => '1', 'group' => 'activation',]);
    }
}
